### ISSUE TITLE
FC8 should not use relu activation

### ISSUE THREAD

**Issue by yongyehuang** [hjptriplebee/AlexNet_with_tensorflow#2]
Thanks for sharing these excellent codes. But I think in the final fc layer('fc8', see the codes below), we should not use the relu activation. Is it right? 
https://github.com/hjptriplebee/AlexNet_with_tensorflow/blob/master/alexnet.py#L92

**Comment by hjptriplebee** [comment]
@yongyehuang Yes. It's a little negligence, but the testing result of the network is still correct. Firstly, relu contains no parameter. So, it does not need any numerical value in model file. Secondly, it doesn't change the partial order relation among different classes. For example, if the result of fc8 shows that A is bigger than B, the result of relu still shows that A is bigger than B.
