### ISSUE TITLE
cannot connect to X server 

### ISSUE THREAD

**Issue by NikAndrush** [hjptriplebee/AlexNet_with_tensorflow#3]
when i run testModel.py, all is ok, the code finds my video card, displays the name of the image and what he saw there, but then gives an error
-------
: cannot connect to X server 
the picture does not appear in the folder with the green text on them as you do

**Comment by hjptriplebee** [comment]
@NikAndrush The result of testModel.py is displayed by a window created by OpenCV, So you can't see pictures with the green text on in the folder. If you can't use function "imshow" in Opencv, It is highly possible that you haven't installed OpenCV correctly.
