### ISSUE TITLE
I want to extract the feature of Convolutional lays. How can I do it？Thanks for the answers

### ISSUE THREAD

**Issue by miraclewxl** [hjptriplebee/AlexNet_with_tensorflow#5]

**Comment by miraclewxl** [comment]
In order to get the conv3 feature, I add the code in the test.py
conv=np(sess.run(alexNet.conv3,feed_dict={x: test}))
However, it didn't work

**Comment by hjptriplebee** [comment]
@miraclewxl Change conv3 to self.conv3 to store its output, and get it in test file with “model.conv3”.
