### ISSUE TITLE
There is no need to split input, split filter number and concatenate two groups of filters

### ISSUE THREAD

**Issue by XiHuYan** [hjptriplebee/AlexNet_with_tensorflow#6]
https://github.com/hjptriplebee/AlexNet_with_tensorflow/blob/1b5a3d616bf5b477b04d88ffea6282b44f97bb07/alexnet.py#L49

**Comment by hjptriplebee** [comment]
从功能上看，确实没有必要，但是论文的作者在文章里描述的是分了两个group，保留这个是为了还原论文.
